/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./resources/js/Components/ui/alert-dialog/AlertDialog.vue')['default']
    AlertDialogAction: typeof import('./resources/js/Components/ui/alert-dialog/AlertDialogAction.vue')['default']
    AlertDialogCancel: typeof import('./resources/js/Components/ui/alert-dialog/AlertDialogCancel.vue')['default']
    AlertDialogContent: typeof import('./resources/js/Components/ui/alert-dialog/AlertDialogContent.vue')['default']
    AlertDialogDescription: typeof import('./resources/js/Components/ui/alert-dialog/AlertDialogDescription.vue')['default']
    AlertDialogFooter: typeof import('./resources/js/Components/ui/alert-dialog/AlertDialogFooter.vue')['default']
    AlertDialogHeader: typeof import('./resources/js/Components/ui/alert-dialog/AlertDialogHeader.vue')['default']
    AlertDialogTitle: typeof import('./resources/js/Components/ui/alert-dialog/AlertDialogTitle.vue')['default']
    AlertDialogTrigger: typeof import('./resources/js/Components/ui/alert-dialog/AlertDialogTrigger.vue')['default']
    ApplicationLogo: typeof import('./resources/js/Components/ApplicationLogo.vue')['default']
    AuthenticatedLayout: typeof import('./resources/js/Layouts/AuthenticatedLayout.vue')['default']
    BarChart: typeof import('./resources/js/Components/BarChart.vue')['default']
    Button: typeof import('./resources/js/Components/ui/button/Button.vue')['default']
    Card: typeof import('./resources/js/Components/ui/card/Card.vue')['default']
    CardContent: typeof import('./resources/js/Components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./resources/js/Components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./resources/js/Components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./resources/js/Components/ui/card/CardHeader.vue')['default']
    CardTenants: typeof import('./resources/js/Components/CardTenants.vue')['default']
    CardTitle: typeof import('./resources/js/Components/ui/card/CardTitle.vue')['default']
    Checkbox: typeof import('./resources/js/Components/Checkbox.vue')['default']
    ConfirmDeleteDialog: typeof import('./resources/js/Components/ConfirmDeleteDialog.vue')['default']
    DangerButton: typeof import('./resources/js/Components/DangerButton.vue')['default']
    Dialog: typeof import('./resources/js/Components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./resources/js/Components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./resources/js/Components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./resources/js/Components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./resources/js/Components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./resources/js/Components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./resources/js/Components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./resources/js/Components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./resources/js/Components/ui/dialog/DialogTrigger.vue')['default']
    Dropdown: typeof import('./resources/js/Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/DropdownLink.vue')['default']
    GuestLayout: typeof import('./resources/js/Layouts/GuestLayout.vue')['default']
    Input: typeof import('./resources/js/Components/ui/input/Input.vue')['default']
    InputError: typeof import('./resources/js/Components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/Components/InputLabel.vue')['default']
    Label: typeof import('./resources/js/Components/ui/label/Label.vue')['default']
    LinkTenantQuestionsDialog: typeof import('./resources/js/Components/LinkTenantQuestionsDialog.vue')['default']
    Modal: typeof import('./resources/js/Components/Modal.vue')['default']
    NavLink: typeof import('./resources/js/Components/NavLink.vue')['default']
    NewEditQuestionDialog: typeof import('./resources/js/Components/NewEditQuestionDialog.vue')['default']
    NewEditTenantDialog: typeof import('./resources/js/Components/NewEditTenantDialog.vue')['default']
    PrimaryButton: typeof import('./resources/js/Components/PrimaryButton.vue')['default']
    QuestionDialog: typeof import('./resources/js/Components/QuestionDialog.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./resources/js/Components/SecondaryButton.vue')['default']
    Sonner: typeof import('./resources/js/Components/ui/sonner/Sonner.vue')['default']
    Table: typeof import('./resources/js/Components/ui/table/Table.vue')['default']
    TableBody: typeof import('./resources/js/Components/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./resources/js/Components/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./resources/js/Components/ui/table/TableCell.vue')['default']
    TableEmpty: typeof import('./resources/js/Components/ui/table/TableEmpty.vue')['default']
    TableFooter: typeof import('./resources/js/Components/ui/table/TableFooter.vue')['default']
    TableHead: typeof import('./resources/js/Components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./resources/js/Components/ui/table/TableHeader.vue')['default']
    TablePatients: typeof import('./resources/js/Components/TablePatients.vue')['default']
    TableQuestions: typeof import('./resources/js/Components/TableQuestions.vue')['default']
    TableRow: typeof import('./resources/js/Components/ui/table/TableRow.vue')['default']
    TableSubmissions: typeof import('./resources/js/Components/TableSubmissions.vue')['default']
    TableTenants: typeof import('./resources/js/Components/TableTenants.vue')['default']
    Textarea: typeof import('./resources/js/Components/ui/textarea/Textarea.vue')['default']
    TextInput: typeof import('./resources/js/Components/TextInput.vue')['default']
  }
}
